version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip
      - unzip terraform_1.5.3_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init

  build:
    commands:
      - echo "Validating Terraform code"
      - terraform validate
      - echo "Planning Terraform changes"
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Applying Terraform changes"
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - "**/*"
  discard-paths: yes
